### ISSUE TITLE
Errors : Too many open files AND /dev/urandom (or equivalent) not found

### ISSUE THREAD

**Issue by lindycoder** [mwilliamson/spur.py#58] opened 2017-01-24 13:53 UTC
Hi, first of all thanks for the lib it's very user friendly !

I've been using it in a monitoring application and i found these 2 errors  (relevant end of the stack traces)

```
  File ".../deployment.py", line 63, in _is_command_success
    shell.run(["bash", "-c", command])
  File ".../lib/python2.7/site-packages/spur/local.py", line 114, in run
    return self.spawn(*args, **kwargs).wait_for_result()
  File ".../lib/python2.7/site-packages/spur/local.py", line 69, in spawn
    **self._subprocess_args(command, *args, **kwargs)
  File "/var/lib/jenkins/.pythonbrew/pythons/Python-2.7/lib/python2.7/subprocess.py", line 672, in __init__
    errread, errwrite)
  File "/var/lib/jenkins/.pythonbrew/pythons/Python-2.7/lib/python2.7/subprocess.py", line 1101, in _execute_child
    errpipe_read, errpipe_write = os.pipe()
OSError: [Errno 24] Too many open files
```

AND 

```
  File ".../deployment.py", line 63, in _is_command_success
    shell.run(["bash", "-c", command])
  File ".../lib/python2.7/site-packages/spur/ssh.py", line 166, in run
    return self.spawn(*args, **kwargs).wait_for_result()
  File ".../lib/python2.7/site-packages/spur/ssh.py", line 178, in spawn
    channel = self._get_ssh_transport().open_session()
  File ".../lib/python2.7/site-packages/spur/ssh.py", line 266, in _get_ssh_transport
    return self._connect_ssh().get_transport()
  File ".../lib/python2.7/site-packages/spur/ssh.py", line 286, in _connect_ssh
    sock=self._sock
  File ".../lib/python2.7/site-packages/paramiko/client.py", line 338, in connect
    t.start_client(timeout=timeout)
  File ".../lib/python2.7/site-packages/paramiko/transport.py", line 499, in start_client
    raise e
NotImplementedError: /dev/urandom (or equivalent) not found
```

# Environment info

These run on an old OS : Debian GNU/Linux 6.0.7 (squeeze)
The base python version of the os is Python 2.6.6 so we use pythonbrew to run 2.7.0
We use virtualenv 1.8.3
We have cryptography 1.4 (because we have OpenSSL 0.9.8o)

## Situational information

These errors don't appear right away. The app was running fine doing stuff with RemoteShell and LocalShell and suddenly, the **first** stack trace happened **once**, and all subsequent calls to shell.run started giving the **second** stack trace, every time.

It happened after approximatively 4000 remote calls with RemoteShell and 1000 local calls with Localshell over 8 days.

# Conclusion

This might be related to the old setup (that's most likely) but in any case it could help anyone  figure out some problems i posted it here.  

And to make this clear, i do use context managers when using the shells

```
with shell as s:
    s.run([...])
```

**Comment by mwilliamson** [comment] 2017-01-24 18:04
I'd guess that the problem with SSH is that it can't open `/dev/urandom` due to to many open files. So, it seems like the problem is that files aren't being closed properly.

**Comment by mwilliamson** [comment] 2017-01-24 23:59
What happens if you repeatedly run commands using just a local shell, or just an SSH shell, or both?

**Comment by mwilliamson** [comment] 2018-10-30 23:06
I don't think there's anything that can be done without more information, so I'm closing this.

**Closed by mwilliamson** 2018-10-30 23:06 UTC
