### ISSUE TITLE
Passing password for sudo commands

### ISSUE THREAD

**Issue by preems** [mwilliamson/spur.py#20] opened 2015-02-17 05:31 UTC
Hi Michael, 
    Thanks for the wonderful library. I wanted to use this library for running sudo commands, which prompt for passwords. As per documentation, there is no way to specify that. I went through the paramiko docs and they have a method to pass the password. I am going through the  source ssh.py and trying to figure out where to modify. I would be great if u could help me on this. Thanks.

**Comment by mwilliamson** [comment] 2015-02-17 22:30
Thanks for the kind words. Could you point me towards the section of the paramiko docs that explain how to pass a password to sudo? What happens if you just write to stdin?

**Comment by foxbunny** [comment] 2015-04-15 11:37
I don't see any response from OP, so I'll mention that writing to STDIN followed by a newline works just fine for me.

**Comment by mwilliamson** [comment] 2015-04-15 21:58
Good to know, thanks!

**Comment by preems** [comment] 2015-04-16 00:36
Thanks. That worked for me too. 
Does this also supports shell features like pipes and reading from bash environment variables ?

**Comment by mwilliamson** [comment] 2015-04-16 07:31
You'd have to explicitly start a bash shell to get access to bash shell features e.g.

```sh
shell.run(["sh", "-c", "echo $PATH"])
```

It seems as if there's no issue here, so I'm closing.

**Closed by mwilliamson** 2015-04-16 07:31 UTC

**Comment by eddawley** [comment] 2016-03-24 15:30
I think this issue should be reopened as spur does not really support SUDO commands that require passwords.  The problem is that there is no way to determine if the connection is waiting on a password from the user so there's no way to tell if you need to write the password to stdin.  This is an inherent problem with the fact that SshProcess() does not expose stdout until the process has completed.

One workaround is that you can run the following first to see if a password will be expected:
`ssh.run(['sudo', '-n', 'whoami'], allow_error=True).return_code`

That workaround is suboptimal though because sudo has a timeout for cached passwords so you never know when you'll run another command that needs you to resend the password.

**Comment by mwilliamson** [comment] 2016-03-25 10:35
> This is an inherent problem with the fact that SshProcess() does not expose stdout until the process has completed.

You can pass in a file-like object in the `stdout` argument, which will be written to as the process runs.
